#!/usr/bin/env python3

# ============================================================
#	Curso   :   Concytec - UTEC
# 	Alumno  :   Jhon Charaja
# 	Info	:	articular PD controller with optimal adaptation 
#				in terms of position and jerk error.
"""
	Notes:
	-----
	- tracking error close to 0
	- system is stable with disturbance 0.95*b and try to reduce tracking error (regular)
	- system is stable with disturbance 0.90*M and reduce tracking error (fast)
	- system is stable with disturbance 0.10*M and reduce tracking error
	- for high disturbances I recommend to use gamma >=0.9
	Updates:
	-------
	- new library to compute dynamic model (pinocchio)
	- new represention of orientation (axis/angle)
	- 
"""
# ============================================================

# ============================
# 			Libraries
# ============================ 
import rospy 							# ROS with Python
import os 								# Manipulate path names
import pandas as pd 					# Save data
from sensor_msgs.msg import JointState 	# To send angular position to robot
from labpythonlib.lab_functions import *
from labpythonlib.lab_markers import *	

# =============
# 	Save data
# =============
origin 	= '../data/PDi'
file_name 	= 'circular_traj'
pwd = os.path.dirname(os.path.realpath(__file__))
folder = os.path.join(pwd, origin, file_name)

# Creates folder if it does not exist
if not os.path.exists(folder):
	os.makedirs(folder)

column_names = [
	't'
	]

df = pd.DataFrame(columns=column_names,dtype=object)


# ===============================
# 		Configuration of node
# ===============================
# Create a nodo: PD_controller
rospy.init_node("PDi_controller_ur5")
# Public in topic /joint_states	to send joint data		
pub = rospy.Publisher('joint_states', JointState, queue_size=1000)
# Loop rate (in Hz)
rate 	= rospy.Rate(100)		# 100 [Hz]
dt 		= 10e-3					# 10  [ms]
# object(message) type JointState
jstate = JointState()

# ===============================
# 		Line and Ball Marker
# ===============================
# Show a ball marker for current and desired position of robot' end-effector
bmarker_des 	= BallMarker(color['GREEN'])
bmarker_act  	= BallMarker(color['YELLOW'])

# =======================================
# 	Set home joint configuration of UR5
# =======================================
#  Home joint configuration of ur5 robot (radians)
q0 = np.array([-0.22007212, -0.72670633, -4.72730825,  0.7416256,   1.57079633, -3.36166477]) # Center [0.5 +0.0 0.0]
dq0 = np.zeros(6)
ddq0 = np.zeros(6)
ddq0 = np.zeros(6) 
# reference trajectory: position, velocity and acceleration
q_ref =   copy(q0)
dq_ref =  np.zeros(6) 
ddq_ref = np.zeros(6) 
dddq_ref = np.zeros(6)
# measured trajectory: position, velocity and acceleration
q_med =   copy(q0)
dq_med =  np.zeros(6) 
ddq_med = np.zeros(6) 
ddq_med = np.zeros(6)
# error trajectory: position, velocity and acceleration
q_e = np.zeros(6)
dq_e =  np.zeros(6) 
ddq_e = np.zeros(6) 
ddq_e = np.zeros(6)

# ===========================
#   UR5 robot configuration
# ===========================
# joints name of UR5 robot
jnames = ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint','wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
# path of labs_ur5.urdf
urdf_path = os.path.join(pwd,'../../ur5_description/urdf/ur5_joint_limited_robot.urdf')
# the class robot load labs_ur5.urdf
ur5_robot = Robot(q0, dq0, dt, urdf_path)
# number of degress of freedom
ndof = ur5_robot.ndof

# create inertia matrix 
M = np.zeros([ndof,ndof])
# create nonlinear effects vector
b = np.zeros(ndof)
# create gravity vector
g = np.zeros(ndof)

# ==============================================
#   set initial cartesian configuration of UR5
# ==============================================
# initial cartesian configuration: position, velocity and acceleration
p0 = np.zeros(7)
p0[0:3], R0 = ur5_robot.forward_kinematics(q0)
p0[3:7] = rot2quat(R0)
dp0 = np.zeros(6)
ddp0 = np.zeros(6)
ddp0 = np.zeros(6)
# desired cartesian trajectory: position, velocity and acceleration
p_des = np.zeros(7)
p_des[0:3] = copy(p0[0:3])
R_des = np.array([[0, 0, 1],[0, 1, 0],[-1, 0, 0]])
#p_des[3:7] = np.array([0.01676998,  0.99985616,  0.00251062,  0.00]) # fixed orientation
dp_des = np.zeros(3)
ddp_des = np.zeros(3)
dddp_des = np.zeros(3)
# reference cartesian trajectory: position, velocity and acceleration
p_ref = np.zeros(7)
p_ref[0:3] = copy(p0[0:3])
p_ref[3:7] = copy(p0[3:7])
dp_ref = np.zeros(6)
ddp_ref = np.zeros(6)
dddp_reef = np.zeros(6)
# measured cartesian trajectory: position, velocity and acceleration
p_med = np.zeros(7)
p_med[0:3] = copy(p0[0:3])
p_med[3:7] = copy(p0[3:7])
dp_med = np.zeros(6)
ddp_med = np.zeros(6)
dddp_med = np.zeros(6)
# Error angular position, velocity and acceleration
p_e    = np.zeros(6)
dp_e   = np.zeros(6)
ddp_e  = np.zeros(6)
dddp_e = np.zeros(6)

# ================================
# 			PD controller
# ================================
alpha = 0.01 # 10 50 80
gamma = 0.9
beta  = 0.1
KP    = np.array([9, 9, 9, 9, 9, 9])
KD    = np.array([6, 6, 6, 6, 6, 6])
dJ_KP = np.zeros(6)
dJ_KD = np.zeros(6)
dKP = np.zeros(6)
dKD = np.zeros(6)

u  = np.zeros(6)
up = np.zeros(6)

# ================================
# 		Dynamic simulation
# ================================
t = 0.0
t_reach = 60 # secs

# Filename
fn = "articular"+"_kp_"+str(KP[0])+"_alpha_"+str(alpha)+"_beta_"+str(beta)+"_gamma_"+str(gamma)+"_t_"+str(t_reach)+".csv"

# save file .csv
path = os.path.join(folder, fn)
df.to_csv(path, index=False)

"""
x = np.array([0.5, 0.0, 0.0])
R = copy(R_des)
q = ur5_robot.inverse_kinematics_pose(x, R, q0)

print("q: ", q)
print("x: ", ur5_robot.forward_kinematics(q))
"""

while not rospy.is_shutdown():
	# desired values (cartesian space)
	p_des[0:3], dp_des[0:3], ddp_des[0:3], dddp_des[0:3] = circular_trayectory_generator(t)
	
	# reference values (cartesian space)
	p_ref[0:3], dp_ref[0:3], ddp_ref[0:3] = reference_trajectory(p_des[0:3], p_ref[0:3], dp_ref[0:3], dt)
	
	# Inverse kinematics
	q_ref = ur5_robot.inverse_kinematics_pose(p_ref[0:3], R_des, q_ref)	# It starts with q_ref=copy(q0)
	
	# jacobian: position xyz [6x6]
	J = ur5_robot.geometric_jacobian(q_ref) 
	# jacobian: dampend pseudo-inverse [6x6] 
	J_pinv = damped_pinv(J)
	# jacobian: time derivative [6x6]
	dJ = ur5_robot.geometric_jacobian_time_derivative(q_ref, dq_ref)

	dq_ref = np.dot(J_pinv, dp_ref)
	ddq_ref = np.dot(J_pinv, ddp_ref - np.dot(dJ, dq_ref))
	
	# Error calculation
	q_e 	=  q_ref - q_med
	dq_e 	=  dq_ref - dq_med
	ddq_e =  ddq_ref - ddq_med

	# Computes inertia matrix
	M  = 0.5*ur5_robot.get_M()
	b = ur5_robot.get_b()
	#b = u - M.dot(ddq_med)
	# SMC articular + Feedback linearization
	u = M.dot(ddq_ref +  np.multiply(KP, q_e) + np.multiply(KD, dq_e)) + b
	
	# Send control signal
	ur5_robot.send_control_command(u)

	# update states
	q_med, dq_med, ddq_med = ur5_robot.read_joint_position_velocity_acceleration()
	p_med[0:3], dp_med[0:3], ddp_med[0:3] = ur5_robot.read_cartesian_position_velocity_acceleration()

	# Publish message
	jstate.header.stamp = rospy.Time.now()
	jstate.name 		= jnames			# Joints position name
	jstate.position 	= q_med
	jstate.velocity 	= dq_med
	pub.publish(jstate)

	# Ball marker
	bmarker_des.xyz(p_ref[0:3])	# Green
	bmarker_act.xyz(p_med[0:3])	# Yellow

	# =========
	# 	error 
	# =========
	# cartesian error
	p_e[0:3] = p_ref[0:3] - p_des[0:3] 

	# ================
	# 	optimization 
	# ================
	# Derivative of Kp and Kd
	dKP = -(alpha/dt) * (dJ_KP)
	dKD = -(alpha/dt) * (dJ_KD)

	# special parameters
	P1 = q_e + KP + KD#+np.multiply(KP, q_e) #+ np.multiply(KD, dq_e)
	P2 = -np.multiply(dKP, q_e)   - np.multiply(KP, dq_e) \
		 -np.multiply(dKD, dq_e) - np.multiply(KD, ddq_e)
	
	#cost function
	c = gamma*0.5*np.dot(P1.T,P1) + beta*0.5*np.dot(P2.T,P2) 	# [1x1]

	# Gradient descent
	dP1_q = -1							# [6x1]
	dP2_q = +copy(dKP) 					# [6x1]	

	# partial derivative of J (cost) with respecto to q(output)
	dJ_q  = gamma*np.multiply(P1, dP1_q) + beta*np.multiply(P2, dP2_q)	# [6x1]
	
	# partial derivative of q (output) with respect to u (control)
	#nonzero = (u!=up) 	# to avoid problems when du=0
	du = (u-up)#*nonzero
	dq_du = np.sign(np.multiply(dq_med, du))
	
	# partial derivative of u (control) with respect to k (control gain)
	du_KP = np.dot(M, q_e)				# [6x1]
	du_KD = np.dot(M, dq_e)   			# [6x1]

	# gradient with respecto to each control gain
	dJ_KP = np.multiply(np.multiply(dJ_q, dq_du), du_KP) 	# [6x1]
	dJ_KD = np.multiply(np.multiply(dJ_q, dq_du), du_KD) 	# [6x1]	

	# New value of KP and KD
	crit_p = (1000)*np.sqrt(np.sum(np.power(p_e[0:3],2))) 	 # [mm]
	crit_a = (180/np.pi)*np.sqrt(np.sum(np.power(q_e[0:6],2))) # [°]
		
	# Upgrade control gains
	KP = KP - alpha*dJ_KP 	#[6x1]  
	KD = KD - alpha*dJ_KD 	#[6x1]	

	# Print
	print("t: ", np.round(t,2))
	print("du: ", dq_du)
	print("KP: ", KP)
	print("KD: ", KD) 
	print("c:  ", c)
	#print("crit_p: ", crit_p)
	#print("crit_a: ", crit_a)
	print("\n")

	# Append data
	row = tl(np.array([t]))
	row = tl(np.expand_dims(np.array(row), axis = 1))
	# Fix for redimensionality
	df_row = pd.DataFrame.from_dict(dict(zip(column_names, row)))
	df.append(df_row, sort = False).to_csv(path, index=False, mode = 'a', header=False)

	# Update
	t = t + dt
	up = copy(u)
	
	if t>=(t_reach): # 60 sec
		print("Reached maximum of steps")
		break

	# Wait for the next iteration
	rate.sleep()
	
print('out because ctrl + c. Data saved.')

