function [rpy_med, rpy_ref, rpy_e] = get_cartesian_orientation_data(data, t_start, t_step, t_end)

rpy_med = 180/pi*[data.roll_med(t_start:t_step:t_end), ...
                   data.pitch_med(t_start:t_step:t_end), ...
                   data.yaw_med(t_start:t_step:t_end)];  

rpy_ref = 180/pi*[data.roll_ref(t_start:t_step:t_end), ...
                 data.pitch_ref(t_start:t_step:t_end), ...
                 data.yaw_ref(t_start:t_step:t_end)];

rpy_e = 180/pi*[data.roll_e(t_start:t_step:t_end), ...
                 data.pitch_e(t_start:t_step:t_end), ...
                 data.yaw_e(t_start:t_step:t_end)];
end