function [K1_1, K2_1, K1_2, K2_2] = get_control_parameters(control_method, data, t_start, t_step, t_end)
len = length(data.t(t_start:t_step:t_end));

if control_method == "SMCi"
    K1_1 = 5*ones(len);
    K2_1 = 1*ones(len);

    K1_2= [    data.L1(t_start:t_step:t_end), ...
                data.L2(t_start:t_step:t_end), ...
                data.L3(t_start:t_step:t_end), ...
                data.L4(t_start:t_step:t_end), ...
                data.L5(t_start:t_step:t_end), ...
                data.L6(t_start:t_step:t_end)]; 
    
    K2_2= [    data.K1(t_start:t_step:t_end), ...
                data.K2(t_start:t_step:t_end), ...
                data.K3(t_start:t_step:t_end), ...
                data.K4(t_start:t_step:t_end), ...
                data.K5(t_start:t_step:t_end), ...
                data.K6(t_start:t_step:t_end)]; 

elseif control_method == "PDi"
    K1_1 = 9*ones(len);
    K2_1 = 6*ones(len);
    
    K1_2= [    data.KP1(t_start:t_step:t_end), ...
                data.KP2(t_start:t_step:t_end), ...
                data.KP3(t_start:t_step:t_end), ...
                data.KP4(t_start:t_step:t_end), ...
                data.KP5(t_start:t_step:t_end), ...
                data.KP6(t_start:t_step:t_end)]; 
    
    K2_2= [    data.KD1(t_start:t_step:t_end), ...
                data.KD2(t_start:t_step:t_end), ...
                data.KD3(t_start:t_step:t_end), ...
                data.KD4(t_start:t_step:t_end), ...
                data.KD5(t_start:t_step:t_end), ...
                data.KD6(t_start:t_step:t_end)];     
end