function [effort_control]=get_effort_control_data(data, t_start, t_step, t_end)

effort_control=[data.u1(t_start:t_step:t_end) ,...
                          data.u2(t_start:t_step:t_end) ,...
                          data.u3(t_start:t_step:t_end) ,...
                          data.u4(t_start:t_step:t_end) ,...
                          data.u5(t_start:t_step:t_end) ,...
                          data.u6(t_start:t_step:t_end)];
end