function [rpy_med, rpy_ref, rpy_e] = get_cartesian_orientation_data(data, t_start, t_step, t_end)

rpy_med = [data.roll_med(t_start:t_step:t_end), ...
                   data.pitch_med(t_start:t_step:t_end), ...
                   data.yaw_med(t_start:t_step:t_end)];  

rpy_ref = [data.roll_ref(t_start:t_step:t_end), ...
                 data.pitch_ref(t_start:t_step:t_end), ...
                 data.yaw_ref(t_start:t_step:t_end)];

rpy_e = rpy_ref - rpy_med;
end