function [q_ref, dq_ref, ddq_ref, q_med, dq_med, ddq_med, q_e, dq_e, ddq_e] = get_cartesian_data(data, t_start, t_step, t_end)
q_ref= [    data.q1_ref(t_start:t_step:t_end), ...
            data.q2_ref(t_start:t_step:t_end), ...
            data.q3_ref(t_start:t_step:t_end), ...
            data.q4_ref(t_start:t_step:t_end), ...
            data.q5_ref(t_start:t_step:t_end), ...
            data.q6_ref(t_start:t_step:t_end)];  
               
dq_ref= [   data.dq1_ref(t_start:t_step:t_end), ...
            data.dq2_ref(t_start:t_step:t_end), ...
            data.dq3_ref(t_start:t_step:t_end), ...
            data.dq4_ref(t_start:t_step:t_end), ...
            data.dq5_ref(t_start:t_step:t_end), ...
            data.dq6_ref(t_start:t_step:t_end)];  

ddq_ref= [  data.ddq1_ref(t_start:t_step:t_end), ...
            data.ddq2_ref(t_start:t_step:t_end), ...
            data.ddq3_ref(t_start:t_step:t_end), ...
            data.ddq4_ref(t_start:t_step:t_end), ...
            data.ddq5_ref(t_start:t_step:t_end), ...
            data.ddq6_ref(t_start:t_step:t_end)];  

% measured data
q_med= [    data.q1_med(t_start:t_step:t_end), ...
                    data.q2_med(t_start:t_step:t_end), ...
                    data.q3_med(t_start:t_step:t_end), ...
                    data.q4_med(t_start:t_step:t_end), ...
                    data.q5_med(t_start:t_step:t_end), ...
                    data.q6_med(t_start:t_step:t_end)];  
               
dq_med= [   data.dq1_med(t_start:t_step:t_end), ...
                    data.dq2_med(t_start:t_step:t_end), ...
                    data.dq3_med(t_start:t_step:t_end), ...
                    data.dq4_med(t_start:t_step:t_end), ...
                    data.dq5_med(t_start:t_step:t_end), ...
                    data.dq6_med(t_start:t_step:t_end)];  

ddq_med= [  data.ddq1_med(t_start:t_step:t_end), ...
                    data.ddq2_med(t_start:t_step:t_end), ...
                    data.ddq3_med(t_start:t_step:t_end), ...
                    data.ddq4_med(t_start:t_step:t_end), ...
                    data.ddq5_med(t_start:t_step:t_end), ...
                    data.ddq6_med(t_start:t_step:t_end)];  

% error data
q_e = q_ref -q_med;
dq_e = dq_ref - dq_med;
ddq_e = ddq_ref - ddq_med;

end