function [x_med, dx_med, ddx_med, x_ref, dx_ref, ddx_ref, x_e, dx_e, ddx_e] = get_cartesian_position_data(data, t_start, t_step, t_end)
% measured
x_med= 1000*[     data.x_med(t_start:t_step:t_end), ...
                    data.y_med(t_start:t_step:t_end), ...
                    data.z_med(t_start:t_step:t_end)];  

dx_med=1000* [   data.dx_med(t_start:t_step:t_end), ...
                    data.dy_med(t_start:t_step:t_end), ...
                    data.dz_med(t_start:t_step:t_end)];  

ddx_med= 1000*[ data.ddx_med(t_start:t_step:t_end), ...
                    data.ddy_med(t_start:t_step:t_end), ...
                    data.ddz_med(t_start:t_step:t_end)];  

% reference
x_ref= 1000*[       data.x_ref(t_start:t_step:t_end), ...
                    data.y_ref(t_start:t_step:t_end), ...
                    data.z_ref(t_start:t_step:t_end)];  

dx_ref= 1000*[     data.dx_ref(t_start:t_step:t_end), ...
                    data.dy_ref(t_start:t_step:t_end), ...
                    data.dz_ref(t_start:t_step:t_end)];  

ddx_ref= 1000*[   data.ddx_ref(t_start:t_step:t_end), ...
                    data.ddy_ref(t_start:t_step:t_end), ...
                    data.ddz_ref(t_start:t_step:t_end)];  

% error
x_e = x_ref - x_med;
dx_e = dx_ref - dx_med;
ddx_e = ddx_ref - ddx_med;

end