joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125
    
# My PD Controller
PD_controller:
  type: effort_controllers/ArticularPDController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint  

